export const CREATE_DICTIONARY = 'CREATE_DICTIONARY'
export const CREATE_DICTIONARY_SUCCESS = 'CREATE_DICTIONARY_SUCCESS'
export const CREATE_DICTIONARY_FAILURE = 'CREATE_DICTIONARY_FAILURE'

export const GET_DICTIONARIES = 'GET_DICTIONARIES'
export const GET_DICTIONARIES_SUCCESS = 'GET_DICTIONARIES_SUCCESS'
export const GET_DICTIONARIES_FAILURE = 'GET_DICTIONARIES_FAILURE'